from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


ScoringDimension = Literal["reach", "engagement", "appropriation", "impact"]
KPIDifficulty = Literal["easy", "medium", "hard"]
KPIProvenance = Literal["measured", "estimated", "declared", "proxy"]
KPICategory = Literal[
    "internal_communication",
    "corporate_event",
    "csr_sustainability",
]


class AdvancedKPIDefinition(BaseModel):
    id: str
    name: str
    description: str
    dimension: ScoringDimension
    category: KPICategory
    unit: str
    formula: str
    required_inputs: list[str] = Field(default_factory=list)
    difficulty: KPIDifficulty
    provenance_default: KPIProvenance
    tags: list[str] = Field(default_factory=list)


ADVANCED_KPIS: list[AdvancedKPIDefinition] = [
    # ------------------------------------------------------------------
    # INTERNAL COMMUNICATION
    # ------------------------------------------------------------------
    AdvancedKPIDefinition(
        id="internal.audience_coverage_rate",
        name="Audience Coverage Rate",
        description="Percentage of the intended audience actually reached by the communication.",
        dimension="reach",
        category="internal_communication",
        unit="percent",
        formula="reached_users / target_audience * 100",
        required_inputs=["reached_users", "target_audience"],
        difficulty="easy",
        provenance_default="measured",
        tags=["reach", "audience", "distribution", "campaign"],
    ),
    AdvancedKPIDefinition(
        id="internal.delivery_rate",
        name="Delivery Rate",
        description="Percentage of sent communications successfully delivered.",
        dimension="reach",
        category="internal_communication",
        unit="percent",
        formula="delivered_messages / sent_messages * 100",
        required_inputs=["delivered_messages", "sent_messages"],
        difficulty="easy",
        provenance_default="measured",
        tags=["email", "delivery", "distribution"],
    ),
    AdvancedKPIDefinition(
        id="internal.open_rate",
        name="Open Rate",
        description="Percentage of delivered messages opened by recipients.",
        dimension="reach",
        category="internal_communication",
        unit="percent",
        formula="opened_messages / delivered_messages * 100",
        required_inputs=["opened_messages", "delivered_messages"],
        difficulty="easy",
        provenance_default="measured",
        tags=["email", "open", "visibility"],
    ),
    AdvancedKPIDefinition(
        id="internal.click_rate",
        name="Click Rate",
        description="Percentage of delivered messages that generated at least one click.",
        dimension="engagement",
        category="internal_communication",
        unit="percent",
        formula="clicks / delivered_messages * 100",
        required_inputs=["clicks", "delivered_messages"],
        difficulty="easy",
        provenance_default="measured",
        tags=["engagement", "click", "email", "intranet"],
    ),
    AdvancedKPIDefinition(
        id="internal.click_to_open_rate",
        name="Click-to-Open Rate",
        description="Percentage of opened communications that generated a click.",
        dimension="engagement",
        category="internal_communication",
        unit="percent",
        formula="clicks / opened_messages * 100",
        required_inputs=["clicks", "opened_messages"],
        difficulty="easy",
        provenance_default="measured",
        tags=["engagement", "click", "quality"],
    ),
    AdvancedKPIDefinition(
        id="internal.participation_rate",
        name="Participation Rate",
        description="Percentage of the target population that took the expected action.",
        dimension="engagement",
        category="internal_communication",
        unit="percent",
        formula="participants / target_audience * 100",
        required_inputs=["participants", "target_audience"],
        difficulty="easy",
        provenance_default="measured",
        tags=["participation", "activation", "engagement"],
    ),
    AdvancedKPIDefinition(
        id="internal.content_consumption_rate",
        name="Content Consumption Rate",
        description="Percentage of exposed users who consumed most or all of the content.",
        dimension="engagement",
        category="internal_communication",
        unit="percent",
        formula="users_reaching_consumption_threshold / exposed_users * 100",
        required_inputs=["users_reaching_consumption_threshold", "exposed_users"],
        difficulty="medium",
        provenance_default="measured",
        tags=["content", "reading", "consumption", "engagement"],
    ),
    AdvancedKPIDefinition(
        id="internal.message_clarity_score",
        name="Message Clarity Score",
        description="Perceived clarity of the communication among recipients.",
        dimension="appropriation",
        category="internal_communication",
        unit="score_100",
        formula="average survey score normalized to 100",
        required_inputs=["survey_clarity_scores"],
        difficulty="easy",
        provenance_default="declared",
        tags=["clarity", "appropriation", "survey"],
    ),
    AdvancedKPIDefinition(
        id="internal.message_understanding_score",
        name="Message Understanding Score",
        description="Degree to which recipients understood the intended message.",
        dimension="appropriation",
        category="internal_communication",
        unit="score_100",
        formula="average quiz or survey score normalized to 100",
        required_inputs=["understanding_scores"],
        difficulty="medium",
        provenance_default="declared",
        tags=["understanding", "appropriation", "quiz"],
    ),
    AdvancedKPIDefinition(
        id="internal.memorization_score",
        name="Memorization Score",
        description="Retention of the key message after the communication.",
        dimension="appropriation",
        category="internal_communication",
        unit="score_100",
        formula="average recall score normalized to 100",
        required_inputs=["memorization_scores"],
        difficulty="medium",
        provenance_default="declared",
        tags=["memory", "recall", "appropriation"],
    ),
    AdvancedKPIDefinition(
        id="internal.usefulness_score",
        name="Usefulness Score",
        description="Perceived practical usefulness of the communication.",
        dimension="appropriation",
        category="internal_communication",
        unit="score_100",
        formula="average survey score normalized to 100",
        required_inputs=["usefulness_scores"],
        difficulty="easy",
        provenance_default="declared",
        tags=["usefulness", "value", "appropriation"],
    ),
    AdvancedKPIDefinition(
        id="internal.alignment_score",
        name="Alignment Score",
        description="Degree to which recipients feel aligned with the objective of the communication.",
        dimension="impact",
        category="internal_communication",
        unit="score_100",
        formula="average alignment survey score normalized to 100",
        required_inputs=["alignment_scores"],
        difficulty="medium",
        provenance_default="declared",
        tags=["alignment", "impact", "strategy"],
    ),
    AdvancedKPIDefinition(
        id="internal.adoption_rate",
        name="Adoption Rate",
        description="Percentage of the target population that adopted the expected tool, process or behavior.",
        dimension="impact",
        category="internal_communication",
        unit="percent",
        formula="adopters / target_population * 100",
        required_inputs=["adopters", "target_population"],
        difficulty="medium",
        provenance_default="measured",
        tags=["adoption", "behavior", "impact"],
    ),
    AdvancedKPIDefinition(
        id="internal.completion_rate",
        name="Completion Rate",
        description="Percentage of users who completed the requested next step.",
        dimension="impact",
        category="internal_communication",
        unit="percent",
        formula="completed_actions / target_population * 100",
        required_inputs=["completed_actions", "target_population"],
        difficulty="easy",
        provenance_default="measured",
        tags=["completion", "action", "impact"],
    ),

    # ------------------------------------------------------------------
    # CORPORATE EVENTS
    # ------------------------------------------------------------------
    AdvancedKPIDefinition(
        id="event.invitation_coverage_rate",
        name="Invitation Coverage Rate",
        description="Percentage of the intended audience invited to the event.",
        dimension="reach",
        category="corporate_event",
        unit="percent",
        formula="invited_population / target_population * 100",
        required_inputs=["invited_population", "target_population"],
        difficulty="easy",
        provenance_default="measured",
        tags=["event", "invitation", "reach"],
    ),
    AdvancedKPIDefinition(
        id="event.registration_rate",
        name="Registration Rate",
        description="Percentage of invited people who registered.",
        dimension="reach",
        category="corporate_event",
        unit="percent",
        formula="registered_participants / invited_population * 100",
        required_inputs=["registered_participants", "invited_population"],
        difficulty="easy",
        provenance_default="measured",
        tags=["event", "registration", "reach"],
    ),
    AdvancedKPIDefinition(
        id="event.attendance_rate",
        name="Attendance Rate",
        description="Percentage of registered participants who actually attended.",
        dimension="reach",
        category="corporate_event",
        unit="percent",
        formula="actual_attendees / registered_participants * 100",
        required_inputs=["actual_attendees", "registered_participants"],
        difficulty="easy",
        provenance_default="measured",
        tags=["attendance", "presence", "event"],
    ),
    AdvancedKPIDefinition(
        id="event.no_show_rate",
        name="No-Show Rate",
        description="Percentage of registered participants who did not attend.",
        dimension="reach",
        category="corporate_event",
        unit="percent",
        formula="no_show_count / registered_participants * 100",
        required_inputs=["no_show_count", "registered_participants"],
        difficulty="easy",
        provenance_default="measured",
        tags=["event", "attendance", "no-show"],
    ),
    AdvancedKPIDefinition(
        id="event.session_participation_rate",
        name="Session Participation Rate",
        description="Percentage of attendees participating in the key sessions or workshops.",
        dimension="engagement",
        category="corporate_event",
        unit="percent",
        formula="session_participants / attendees * 100",
        required_inputs=["session_participants", "attendees"],
        difficulty="medium",
        provenance_default="measured",
        tags=["session", "participation", "engagement"],
    ),
    AdvancedKPIDefinition(
        id="event.live_interaction_rate",
        name="Live Interaction Rate",
        description="Percentage of attendees who interacted during the event through Q&A, voting, chat or activities.",
        dimension="engagement",
        category="corporate_event",
        unit="percent",
        formula="interacting_attendees / attendees * 100",
        required_inputs=["interacting_attendees", "attendees"],
        difficulty="medium",
        provenance_default="measured",
        tags=["interaction", "live", "engagement"],
    ),
    AdvancedKPIDefinition(
        id="event.networking_rate",
        name="Networking Rate",
        description="Share of attendees reporting meaningful exchanges or new useful connections.",
        dimension="engagement",
        category="corporate_event",
        unit="percent",
        formula="attendees_reporting_networking / attendees * 100",
        required_inputs=["attendees_reporting_networking", "attendees"],
        difficulty="medium",
        provenance_default="declared",
        tags=["networking", "engagement", "connections"],
    ),
    AdvancedKPIDefinition(
        id="event.satisfaction_score",
        name="Satisfaction Score",
        description="Overall post-event satisfaction score.",
        dimension="appropriation",
        category="corporate_event",
        unit="score_100",
        formula="average satisfaction score normalized to 100",
        required_inputs=["satisfaction_scores"],
        difficulty="easy",
        provenance_default="declared",
        tags=["satisfaction", "experience", "event"],
    ),
    AdvancedKPIDefinition(
        id="event.inspiration_score",
        name="Inspiration Score",
        description="Extent to which the event energized and inspired participants.",
        dimension="appropriation",
        category="corporate_event",
        unit="score_100",
        formula="average inspiration survey score normalized to 100",
        required_inputs=["inspiration_scores"],
        difficulty="medium",
        provenance_default="declared",
        tags=["inspiration", "appropriation", "event"],
    ),
    AdvancedKPIDefinition(
        id="event.usefulness_score",
        name="Usefulness Score",
        description="Perceived usefulness of event content and exchanges.",
        dimension="appropriation",
        category="corporate_event",
        unit="score_100",
        formula="average usefulness survey score normalized to 100",
        required_inputs=["usefulness_scores"],
        difficulty="easy",
        provenance_default="declared",
        tags=["usefulness", "appropriation", "content"],
    ),
    AdvancedKPIDefinition(
        id="event.memorization_score",
        name="Memorization Score",
        description="Retention of the key messages delivered during the event.",
        dimension="appropriation",
        category="corporate_event",
        unit="score_100",
        formula="average recall score normalized to 100",
        required_inputs=["memorization_scores"],
        difficulty="medium",
        provenance_default="declared",
        tags=["memory", "messages", "appropriation"],
    ),
    AdvancedKPIDefinition(
        id="event.strategic_alignment_score",
        name="Strategic Alignment Score",
        description="Degree to which attendees feel more aligned with company direction after the event.",
        dimension="impact",
        category="corporate_event",
        unit="score_100",
        formula="average alignment survey score normalized to 100",
        required_inputs=["alignment_scores"],
        difficulty="medium",
        provenance_default="declared",
        tags=["alignment", "strategy", "impact"],
    ),
    AdvancedKPIDefinition(
        id="event.intent_to_act_score",
        name="Intent-to-Act Score",
        description="Extent to which participants intend to apply ideas or actions after the event.",
        dimension="impact",
        category="corporate_event",
        unit="score_100",
        formula="average intent-to-act survey score normalized to 100",
        required_inputs=["intent_to_act_scores"],
        difficulty="medium",
        provenance_default="declared",
        tags=["activation", "intent", "impact"],
    ),
    AdvancedKPIDefinition(
        id="event.post_event_activation_rate",
        name="Post-Event Activation Rate",
        description="Percentage of attendees who completed a follow-up action after the event.",
        dimension="impact",
        category="corporate_event",
        unit="percent",
        formula="attendees_completing_followup / attendees * 100",
        required_inputs=["attendees_completing_followup", "attendees"],
        difficulty="medium",
        provenance_default="measured",
        tags=["follow-up", "activation", "impact"],
    ),
    AdvancedKPIDefinition(
        id="event.cohesion_perception_score",
        name="Cohesion Perception Score",
        description="Degree to which the event improved team cohesion and collective momentum.",
        dimension="impact",
        category="corporate_event",
        unit="score_100",
        formula="average cohesion survey score normalized to 100",
        required_inputs=["cohesion_scores"],
        difficulty="medium",
        provenance_default="declared",
        tags=["cohesion", "culture", "impact"],
    ),

    # ------------------------------------------------------------------
    # CSR / SUSTAINABILITY
    # ------------------------------------------------------------------
    AdvancedKPIDefinition(
        id="csr.participant_coverage_rate",
        name="Participant Coverage Rate",
        description="Share of participants included in the CSR measurement perimeter.",
        dimension="reach",
        category="csr_sustainability",
        unit="percent",
        formula="participants_measured / total_participants * 100",
        required_inputs=["participants_measured", "total_participants"],
        difficulty="easy",
        provenance_default="measured",
        tags=["csr", "scope", "coverage"],
    ),
    AdvancedKPIDefinition(
        id="csr.rse_message_visibility_rate",
        name="RSE Message Visibility Rate",
        description="Percentage of the audience exposed to the CSR message or information layer.",
        dimension="reach",
        category="csr_sustainability",
        unit="percent",
        formula="audience_exposed_to_rse_message / target_audience * 100",
        required_inputs=["audience_exposed_to_rse_message", "target_audience"],
        difficulty="easy",
        provenance_default="measured",
        tags=["rse", "communication", "reach"],
    ),
    AdvancedKPIDefinition(
        id="csr.engagement_rate",
        name="CSR Engagement Rate",
        description="Percentage of participants who interacted with the CSR content or actions.",
        dimension="engagement",
        category="csr_sustainability",
        unit="percent",
        formula="engaged_participants / total_participants * 100",
        required_inputs=["engaged_participants", "total_participants"],
        difficulty="medium",
        provenance_default="measured",
        tags=["rse", "engagement", "participation"],
    ),
    AdvancedKPIDefinition(
        id="csr.local_supplier_rate",
        name="Local Supplier Rate",
        description="Percentage of suppliers sourced locally.",
        dimension="engagement",
        category="csr_sustainability",
        unit="percent",
        formula="local_suppliers / total_suppliers * 100",
        required_inputs=["local_suppliers", "total_suppliers"],
        difficulty="medium",
        provenance_default="measured",
        tags=["suppliers", "local", "rse"],
    ),
    AdvancedKPIDefinition(
        id="csr.responsible_supplier_rate",
        name="Responsible Supplier Rate",
        description="Percentage of suppliers meeting responsible procurement criteria.",
        dimension="engagement",
        category="csr_sustainability",
        unit="percent",
        formula="responsible_suppliers / total_suppliers * 100",
        required_inputs=["responsible_suppliers", "total_suppliers"],
        difficulty="medium",
        provenance_default="declared",
        tags=["procurement", "suppliers", "responsible"],
    ),
    AdvancedKPIDefinition(
        id="csr.accessibility_score",
        name="Accessibility Score",
        description="Score reflecting the accessibility and inclusiveness of the operation.",
        dimension="appropriation",
        category="csr_sustainability",
        unit="score_100",
        formula="checklist-based accessibility score normalized to 100",
        required_inputs=["accessibility_checklist_score"],
        difficulty="medium",
        provenance_default="proxy",
        tags=["accessibility", "inclusion", "rse"],
    ),
    AdvancedKPIDefinition(
        id="csr.rse_coherence_score",
        name="RSE Coherence Score",
        description="Perceived coherence between the sustainability message and the actual implementation.",
        dimension="appropriation",
        category="csr_sustainability",
        unit="score_100",
        formula="average coherence survey score normalized to 100",
        required_inputs=["coherence_scores"],
        difficulty="medium",
        provenance_default="declared",
        tags=["coherence", "credibility", "rse"],
    ),
    AdvancedKPIDefinition(
        id="csr.inclusion_perception_score",
        name="Inclusion Perception Score",
        description="Perceived inclusiveness and fairness of the operation.",
        dimension="appropriation",
        category="csr_sustainability",
        unit="score_100",
        formula="average inclusion survey score normalized to 100",
        required_inputs=["inclusion_scores"],
        difficulty="medium",
        provenance_default="declared",
        tags=["inclusion", "perception", "rse"],
    ),
    AdvancedKPIDefinition(
        id="csr.estimated_carbon_footprint",
        name="Estimated Carbon Footprint",
        description="Estimated total carbon footprint of the operation.",
        dimension="impact",
        category="csr_sustainability",
        unit="kg_co2e",
        formula="transport + venue + catering + lodging + logistics emissions",
        required_inputs=["transport_emissions", "venue_emissions", "catering_emissions", "lodging_emissions", "logistics_emissions"],
        difficulty="medium",
        provenance_default="estimated",
        tags=["carbon", "emissions", "impact"],
    ),
    AdvancedKPIDefinition(
        id="csr.carbon_per_participant",
        name="Carbon per Participant",
        description="Average carbon footprint per participant.",
        dimension="impact",
        category="csr_sustainability",
        unit="kg_co2e",
        formula="total_carbon / total_participants",
        required_inputs=["total_carbon", "total_participants"],
        difficulty="easy",
        provenance_default="estimated",
        tags=["carbon", "participant", "impact"],
    ),
    AdvancedKPIDefinition(
        id="csr.transport_emission_share",
        name="Transport Emission Share",
        description="Percentage of total emissions generated by transport.",
        dimension="impact",
        category="csr_sustainability",
        unit="percent",
        formula="transport_emissions / total_carbon * 100",
        required_inputs=["transport_emissions", "total_carbon"],
        difficulty="medium",
        provenance_default="estimated",
        tags=["transport", "carbon", "impact"],
    ),
    AdvancedKPIDefinition(
        id="csr.waste_reduction_score",
        name="Waste Reduction Score",
        description="Score reflecting waste prevention, reduction and sorting efforts.",
        dimension="impact",
        category="csr_sustainability",
        unit="score_100",
        formula="rule-based waste reduction score normalized to 100",
        required_inputs=["waste_reduction_inputs"],
        difficulty="hard",
        provenance_default="proxy",
        tags=["waste", "reduction", "impact"],
    ),
    AdvancedKPIDefinition(
        id="csr.sobriety_score",
        name="Sobriety Score",
        description="Overall score reflecting the frugality and resource efficiency of the operation.",
        dimension="impact",
        category="csr_sustainability",
        unit="score_100",
        formula="weighted rule-based score from logistics, carbon and production choices",
        required_inputs=["sobriety_inputs"],
        difficulty="hard",
        provenance_default="proxy",
        tags=["sobriety", "efficiency", "impact"],
    ),
]


def get_kpi_by_id(kpi_id: str) -> AdvancedKPIDefinition | None:
    for kpi in ADVANCED_KPIS:
        if kpi.id == kpi_id:
            return kpi
    return None


def get_dimension_from_kpi(kpi_id: str) -> ScoringDimension:
    kpi = get_kpi_by_id(kpi_id)
    if not kpi:
        raise KeyError(f"Unknown KPI id: {kpi_id}")
    return kpi.dimension


def recommend_kpis(
    initiative_type: str,
    goals: list[str] | None = None,
) -> list[AdvancedKPIDefinition]:
    goals = [goal.lower() for goal in (goals or [])]

    filtered = [kpi for kpi in ADVANCED_KPIS if kpi.category == initiative_type]
    if not goals:
        return filtered[:8]

    scored: list[tuple[int, AdvancedKPIDefinition]] = []
    for kpi in filtered:
        score = 0
        searchable = " ".join([kpi.name, kpi.description, *kpi.tags]).lower()
        for goal in goals:
            if goal in searchable:
                score += 2
            for word in goal.split():
                if word in searchable:
                    score += 1
        scored.append((score, kpi))

    scored.sort(key=lambda item: item[0], reverse=True)
    ranked = [kpi for score, kpi in scored if score > 0]

    return ranked[:8] if ranked else filtered[:8]