/**
 * Catalogue conversationnel des KPIs Momentum — port depuis
 * momentum/apps/web/src/app/diagnostic/page.tsx (KPI_PLAN).
 *
 * 8-10 KPIs par type d'initiative, répartis sur les 4 dimensions
 * (reach / engagement / appropriation / impact).
 */

import type { InitiativeType, KPIQuestion, RSEKPIQuestion } from "./types";

export const KPI_PLAN: Record<InitiativeType, KPIQuestion[]> = {
  corporate_event: [
    { kpiId: "event.invitation_coverage_rate", dimension: "reach", label: "Couverture des invitations",
      helper: "Invités atteints / population cible initiale.",
      unitHint: "% — ex. 92", defaultProvenance: "measured" },
    { kpiId: "event.registration_rate", dimension: "reach", label: "Taux d'inscription",
      helper: "Inscrits / invités ayant reçu la convocation.",
      unitHint: "% — ex. 78", defaultProvenance: "measured" },
    { kpiId: "event.attendance_rate", dimension: "reach", label: "Taux de participation réel",
      helper: "Participants présents / participants inscrits.",
      unitHint: "% — ex. 72", defaultProvenance: "measured" },
    { kpiId: "event.session_participation_rate", dimension: "engagement", label: "Participation aux sessions",
      helper: "Part des sessions suivies par rapport au programme total.",
      unitHint: "% — ex. 65", defaultProvenance: "measured" },
    { kpiId: "event.live_interaction_rate", dimension: "engagement", label: "Taux d'interaction en direct",
      helper: "Présents ayant posé une question, voté, ou interagi.",
      unitHint: "% — ex. 45", defaultProvenance: "measured" },
    { kpiId: "event.networking_rate", dimension: "engagement", label: "Taux de networking",
      helper: "Part des participants ayant échangé entre eux (apps, tables…).",
      unitHint: "% — ex. 35", defaultProvenance: "estimated" },
    { kpiId: "event.satisfaction_score", dimension: "appropriation", label: "Score de satisfaction",
      helper: "Note moyenne de satisfaction post-événement ramenée sur 100.",
      unitHint: "0-100 — ex. 66", defaultProvenance: "declared" },
    { kpiId: "event.memorization_score", dimension: "appropriation", label: "Score de mémorisation",
      helper: "Capacité à restituer les messages clés (quiz, sondage).",
      unitHint: "0-100 — ex. 58", defaultProvenance: "declared" },
    { kpiId: "event.inspiration_score", dimension: "appropriation", label: "Score d'inspiration",
      helper: "Dans quelle mesure l'événement a-t-il inspiré / motivé ?",
      unitHint: "0-100 — ex. 62", defaultProvenance: "declared" },
    { kpiId: "event.strategic_alignment_score", dimension: "impact", label: "Alignement stratégique perçu",
      helper: "Les participants se sentent-ils plus alignés sur la direction ?",
      unitHint: "0-100 — ex. 60", defaultProvenance: "declared" },
    { kpiId: "event.intent_to_act_score", dimension: "impact", label: "Intention d'agir",
      helper: "Proportion déclarant vouloir agir suite à l'événement.",
      unitHint: "0-100 — ex. 55", defaultProvenance: "declared" },
    { kpiId: "event.post_event_activation_rate", dimension: "impact", label: "Activation post-événement",
      helper: "Participants ayant posé une action concrète après l'événement.",
      unitHint: "% — ex. 30", defaultProvenance: "measured" },
  ],
  digital_campaign: [
    { kpiId: "internal.audience_coverage_rate", dimension: "reach", label: "Taux de couverture",
      helper: "Personnes effectivement touchées / audience cible.",
      unitHint: "% — ex. 80", defaultProvenance: "measured" },
    { kpiId: "internal.delivery_rate", dimension: "reach", label: "Taux de délivrabilité",
      helper: "Messages délivrés / messages envoyés.",
      unitHint: "% — ex. 97", defaultProvenance: "measured" },
    { kpiId: "internal.open_rate", dimension: "reach", label: "Taux d'ouverture",
      helper: "Messages ouverts / messages délivrés.",
      unitHint: "% — ex. 40", defaultProvenance: "measured" },
    { kpiId: "internal.click_rate", dimension: "engagement", label: "Taux de clic",
      helper: "Clics générés / messages délivrés.",
      unitHint: "% — ex. 8", defaultProvenance: "measured" },
    { kpiId: "internal.content_consumption_rate", dimension: "engagement", label: "Consommation du contenu",
      helper: "Part des utilisateurs ayant consulté plus de la moitié du contenu.",
      unitHint: "% — ex. 55", defaultProvenance: "measured" },
    { kpiId: "internal.message_clarity_score", dimension: "appropriation", label: "Clarté perçue du message",
      helper: "Note moyenne de clarté ramenée sur 100.",
      unitHint: "0-100 — ex. 75", defaultProvenance: "declared" },
    { kpiId: "internal.memorization_score", dimension: "appropriation", label: "Mémorisation du message",
      helper: "Capacité à citer le message principal de la campagne.",
      unitHint: "0-100 — ex. 60", defaultProvenance: "declared" },
    { kpiId: "internal.usefulness_score", dimension: "appropriation", label: "Utilité perçue",
      helper: "Le message est-il perçu comme utile par l'audience ?",
      unitHint: "0-100 — ex. 65", defaultProvenance: "declared" },
    { kpiId: "internal.alignment_score", dimension: "impact", label: "Alignement avec l'objectif",
      helper: "Degré d'alignement perçu avec l'objectif de la campagne.",
      unitHint: "0-100 — ex. 65", defaultProvenance: "declared" },
    { kpiId: "internal.completion_rate", dimension: "impact", label: "Taux de complétion",
      helper: "Personnes ayant réalisé l'action attendue / population cible.",
      unitHint: "% — ex. 25", defaultProvenance: "measured" },
  ],
  change_management: [
    { kpiId: "internal.audience_coverage_rate", dimension: "reach", label: "Couverture de l'audience",
      helper: "Part de la population cible effectivement informée.",
      unitHint: "% — ex. 85", defaultProvenance: "measured" },
    { kpiId: "internal.open_rate", dimension: "reach", label: "Taux d'ouverture",
      helper: "Messages lus / messages envoyés (briefs, communications officielles).",
      unitHint: "% — ex. 55", defaultProvenance: "measured" },
    { kpiId: "internal.participation_rate", dimension: "engagement", label: "Taux de participation",
      helper: "Personnes ayant pris part aux moments clés (ateliers, briefs…).",
      unitHint: "% — ex. 60", defaultProvenance: "measured" },
    { kpiId: "internal.click_rate", dimension: "engagement", label: "Interaction avec les supports",
      helper: "Clics / interactions sur les supports de communication dédiés.",
      unitHint: "% — ex. 22", defaultProvenance: "measured" },
    { kpiId: "internal.message_understanding_score", dimension: "appropriation", label: "Compréhension du changement",
      helper: "Les collaborateurs comprennent-ils ce qui change et pourquoi ?",
      unitHint: "0-100 — ex. 55", defaultProvenance: "declared" },
    { kpiId: "internal.message_clarity_score", dimension: "appropriation", label: "Clarté du discours",
      helper: "Clarté perçue du discours managérial sur le changement.",
      unitHint: "0-100 — ex. 60", defaultProvenance: "declared" },
    { kpiId: "internal.usefulness_score", dimension: "appropriation", label: "Utilité perçue",
      helper: "Le changement est-il perçu comme utile à leur activité ?",
      unitHint: "0-100 — ex. 60", defaultProvenance: "declared" },
    { kpiId: "internal.adoption_rate", dimension: "impact", label: "Taux d'adoption",
      helper: "Personnes ayant adopté le nouveau processus / outil.",
      unitHint: "% — ex. 40", defaultProvenance: "measured" },
    { kpiId: "internal.alignment_score", dimension: "impact", label: "Alignement sur la direction",
      helper: "Degré d'adhésion à la nouvelle direction.",
      unitHint: "0-100 — ex. 58", defaultProvenance: "declared" },
    { kpiId: "internal.completion_rate", dimension: "impact", label: "Complétion des actions attendues",
      helper: "Part des étapes du plan de change effectivement réalisées.",
      unitHint: "% — ex. 50", defaultProvenance: "measured" },
  ],
  newsletter: [
    { kpiId: "internal.audience_coverage_rate", dimension: "reach", label: "Couverture de l'audience",
      helper: "Abonnés / population cible théorique.",
      unitHint: "% — ex. 90", defaultProvenance: "measured" },
    { kpiId: "internal.delivery_rate", dimension: "reach", label: "Taux de délivrabilité",
      helper: "Emails délivrés / emails envoyés.",
      unitHint: "% — ex. 98", defaultProvenance: "measured" },
    { kpiId: "internal.open_rate", dimension: "reach", label: "Taux d'ouverture",
      helper: "Emails ouverts / emails délivrés.",
      unitHint: "% — ex. 42", defaultProvenance: "measured" },
    { kpiId: "internal.click_to_open_rate", dimension: "engagement", label: "Taux de clic sur ouverture",
      helper: "Clics / ouvertures — qualité réelle du contenu.",
      unitHint: "% — ex. 18", defaultProvenance: "measured" },
    { kpiId: "internal.content_consumption_rate", dimension: "engagement", label: "Temps de lecture moyen",
      helper: "Part des lecteurs ayant consommé l'essentiel de la newsletter.",
      unitHint: "% — ex. 45", defaultProvenance: "estimated" },
    { kpiId: "internal.message_clarity_score", dimension: "appropriation", label: "Clarté du message",
      helper: "Note de clarté ramenée sur 100.",
      unitHint: "0-100 — ex. 70", defaultProvenance: "declared" },
    { kpiId: "internal.usefulness_score", dimension: "appropriation", label: "Utilité perçue",
      helper: "Valeur perçue du contenu par les lecteurs.",
      unitHint: "0-100 — ex. 65", defaultProvenance: "declared" },
    { kpiId: "internal.alignment_score", dimension: "impact", label: "Alignement avec la ligne éditoriale",
      helper: "Cohérence perçue avec les messages stratégiques.",
      unitHint: "0-100 — ex. 60", defaultProvenance: "declared" },
    { kpiId: "internal.completion_rate", dimension: "impact", label: "Action réalisée",
      helper: "Lecteurs ayant réalisé l'action attendue.",
      unitHint: "% — ex. 12", defaultProvenance: "measured" },
  ],
  product_launch: [
    { kpiId: "internal.audience_coverage_rate", dimension: "reach", label: "Couverture du lancement",
      helper: "Audience cible effectivement touchée par l'annonce.",
      unitHint: "% — ex. 80", defaultProvenance: "measured" },
    { kpiId: "internal.open_rate", dimension: "reach", label: "Taux d'ouverture des annonces",
      helper: "Annonces ouvertes / annonces délivrées.",
      unitHint: "% — ex. 50", defaultProvenance: "measured" },
    { kpiId: "internal.participation_rate", dimension: "engagement", label: "Participation aux temps forts",
      helper: "Participation aux webinars, démos, Q&A.",
      unitHint: "% — ex. 50", defaultProvenance: "measured" },
    { kpiId: "internal.click_rate", dimension: "engagement", label: "Clics sur les supports produit",
      helper: "Clics vers la landing / démos / docs produit.",
      unitHint: "% — ex. 15", defaultProvenance: "measured" },
    { kpiId: "internal.memorization_score", dimension: "appropriation", label: "Mémorisation des bénéfices",
      helper: "Capacité à citer les bénéfices clés du produit.",
      unitHint: "0-100 — ex. 60", defaultProvenance: "declared" },
    { kpiId: "internal.message_clarity_score", dimension: "appropriation", label: "Clarté du positionnement",
      helper: "Le positionnement produit est-il clair pour la cible ?",
      unitHint: "0-100 — ex. 65", defaultProvenance: "declared" },
    { kpiId: "internal.usefulness_score", dimension: "appropriation", label: "Utilité perçue du produit",
      helper: "Le produit répond-il à un besoin réel ?",
      unitHint: "0-100 — ex. 70", defaultProvenance: "declared" },
    { kpiId: "internal.adoption_rate", dimension: "impact", label: "Taux d'adoption",
      helper: "Utilisateurs ayant réellement adopté le produit.",
      unitHint: "% — ex. 35", defaultProvenance: "measured" },
    { kpiId: "internal.alignment_score", dimension: "impact", label: "Alignement avec la stratégie",
      helper: "Cohérence perçue avec la vision / roadmap globale.",
      unitHint: "0-100 — ex. 65", defaultProvenance: "declared" },
  ],
  other: [
    { kpiId: "internal.audience_coverage_rate", dimension: "reach", label: "Couverture de l'audience",
      helper: "Part de l'audience cible effectivement touchée.",
      unitHint: "% — ex. 70", defaultProvenance: "measured" },
    { kpiId: "internal.delivery_rate", dimension: "reach", label: "Taux de diffusion effective",
      helper: "Communications effectivement reçues / communications prévues.",
      unitHint: "% — ex. 95", defaultProvenance: "measured" },
    { kpiId: "internal.participation_rate", dimension: "engagement", label: "Taux de participation / interaction",
      helper: "Participants actifs / audience cible.",
      unitHint: "% — ex. 40", defaultProvenance: "measured" },
    { kpiId: "internal.message_clarity_score", dimension: "appropriation", label: "Clarté du message",
      helper: "Clarté perçue du message principal.",
      unitHint: "0-100 — ex. 60", defaultProvenance: "declared" },
    { kpiId: "internal.usefulness_score", dimension: "appropriation", label: "Utilité perçue",
      helper: "Valeur ressentie par l'audience.",
      unitHint: "0-100 — ex. 60", defaultProvenance: "declared" },
    { kpiId: "internal.alignment_score", dimension: "impact", label: "Alignement avec l'objectif",
      helper: "Degré d'alignement perçu avec l'objectif de l'action.",
      unitHint: "0-100 — ex. 55", defaultProvenance: "declared" },
    { kpiId: "internal.completion_rate", dimension: "impact", label: "Taux de complétion",
      helper: "Part des actions attendues effectivement réalisées.",
      unitHint: "% — ex. 45", defaultProvenance: "measured" },
  ],
};

export const INITIATIVE_OPTIONS: { id: InitiativeType; label: string }[] = [
  { id: "corporate_event", label: "Événement interne" },
  { id: "digital_campaign", label: "Campagne digitale" },
  { id: "change_management", label: "Plan de change management" },
  { id: "newsletter", label: "Newsletter / email" },
  { id: "product_launch", label: "Lancement produit / projet" },
  { id: "other", label: "Autre" },
];

export const AUDIENCE_OPTIONS = [
  "Tous collaborateurs",
  "Managers",
  "COMEX",
  "Équipe projet",
  "Public externe",
  "Mixte",
];

export const INTENT_OPTIONS = [
  "Informer",
  "Mobiliser",
  "Engager",
  "Expliquer un changement",
  "Célébrer",
  "Aligner",
];

/**
 * Catalogue RSE — 13 indicateurs ESG universels, applicables à toute
 * initiative de communication. Les kpiId sont alignés sur le mapping
 * `RSE_KPI_DIMENSION` de lib/momentum/rse.ts et sur les modèles Python
 * du backend. Les valeurs sont toutes normalisées 0-100 "plus c'est
 * haut, mieux c'est", à l'exception de `csr.transport_emission_share`
 * (inversée dans rse.ts).
 */
export const RSE_KPIS: RSEKPIQuestion[] = [
  /* ─── Environnement ─── */
  {
    kpiId: "csr.estimated_carbon_footprint",
    rseDimension: "environment",
    label: "Maîtrise de l'empreinte carbone",
    helper:
      "Dans quelle mesure l'empreinte carbone globale de l'opération (transport, restauration, supports) est-elle connue et maîtrisée par rapport à une opération comparable ?",
    unitHint: "0-100 — 100 = maîtrise totale",
    defaultProvenance: "estimated",
  },
  {
    kpiId: "csr.carbon_per_participant",
    rseDimension: "environment",
    label: "Sobriété carbone par participant",
    helper:
      "Note de sobriété carbone ramenée au participant (0 = très émissif, 100 = très sobre).",
    unitHint: "0-100 — ex. 55",
    defaultProvenance: "estimated",
  },
  {
    kpiId: "csr.transport_emission_share",
    rseDimension: "environment",
    label: "Part des émissions liées au transport",
    helper:
      "Pourcentage de l'empreinte carbone attribuable aux déplacements des participants. Plus c'est bas, mieux c'est — la valeur est inversée dans le score.",
    unitHint: "% — ex. 65",
    defaultProvenance: "estimated",
  },
  {
    kpiId: "csr.waste_reduction_score",
    rseDimension: "environment",
    label: "Score de réduction des déchets",
    helper:
      "Qualité des dispositifs anti-déchets mis en place (contenants réutilisables, tri, digital over print…).",
    unitHint: "0-100 — ex. 60",
    defaultProvenance: "declared",
  },
  {
    kpiId: "csr.sobriety_score",
    rseDimension: "environment",
    label: "Sobriété des supports",
    helper:
      "Degré de sobriété des supports événementiels et communicationnels (goodies, impressions, décor, énergie).",
    unitHint: "0-100 — ex. 55",
    defaultProvenance: "declared",
  },

  /* ─── Social ─── */
  {
    kpiId: "csr.participant_coverage_rate",
    rseDimension: "social",
    label: "Couverture RSE des participants",
    helper:
      "Part des participants effectivement exposés à des messages ou dispositifs RSE pendant l'opération.",
    unitHint: "% — ex. 70",
    defaultProvenance: "measured",
  },
  {
    kpiId: "csr.rse_message_visibility_rate",
    rseDimension: "social",
    label: "Visibilité des messages RSE",
    helper:
      "Part des communications de l'opération qui intègrent explicitement un message RSE (engagement, action, chiffre).",
    unitHint: "% — ex. 40",
    defaultProvenance: "measured",
  },
  {
    kpiId: "csr.engagement_rate",
    rseDimension: "social",
    label: "Engagement sur les messages RSE",
    helper:
      "Interaction des participants avec les contenus RSE (lectures, clics, questions, participation aux ateliers).",
    unitHint: "% — ex. 35",
    defaultProvenance: "measured",
  },
  {
    kpiId: "csr.accessibility_score",
    rseDimension: "social",
    label: "Score d'accessibilité",
    helper:
      "Accessibilité réelle de l'opération : lieu, supports, format, langues, publics en situation de handicap.",
    unitHint: "0-100 — ex. 65",
    defaultProvenance: "declared",
  },
  {
    kpiId: "csr.inclusion_perception_score",
    rseDimension: "social",
    label: "Perception d'inclusion",
    helper:
      "Sentiment d'inclusion et de représentation rapporté par les participants (enquête post-opération).",
    unitHint: "0-100 — ex. 68",
    defaultProvenance: "declared",
  },

  /* ─── Gouvernance ─── */
  {
    kpiId: "csr.local_supplier_rate",
    rseDimension: "governance",
    label: "Part des fournisseurs locaux",
    helper:
      "Pourcentage de prestataires de l'opération localisés dans le même bassin économique que l'entreprise.",
    unitHint: "% — ex. 60",
    defaultProvenance: "measured",
  },
  {
    kpiId: "csr.responsible_supplier_rate",
    rseDimension: "governance",
    label: "Part des fournisseurs responsables",
    helper:
      "Part des prestataires disposant d'une certification RSE / labellisation reconnue (ISO 26000, B-Corp, Ecovadis…).",
    unitHint: "% — ex. 45",
    defaultProvenance: "measured",
  },
  {
    kpiId: "csr.rse_coherence_score",
    rseDimension: "governance",
    label: "Cohérence RSE de l'opération",
    helper:
      "Rattachement explicite de l'opération à des objectifs RSE formalisés, chiffrés et suivis dans le temps.",
    unitHint: "0-100 — ex. 55",
    defaultProvenance: "declared",
  },
];
