// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const STUDIO_OUTPUT_SCHEMA: Record<string, any> = {
  type: "object",
  properties: {
    projectType: { type: "string", enum: ["transformation", "crise", "rh-social", "corporate", "deploiement-outil", "change-culturel", "reorganisation", "performance"] },
    executiveSummary: { type: "string" },
    communicationDiagnostic: { type: "string" },
    centralProblem: { type: "string" },
    strategicAngle: { type: "string" },
    deviceArchitecture: { type: "string" },
    audienceMessages: {
      type: "array",
      items: {
        type: "object",
        properties: { audience: { type: "string" }, message: { type: "string" }, channel: { type: "string" } },
        required: ["audience", "message", "channel"],
        additionalProperties: false,
      },
    },
    channelMix: { type: "array", items: { type: "string" } },
    keyMessages: { type: "array", items: { type: "string" } },
    timeline: {
      type: "array",
      items: {
        type: "object",
        properties: {
          when: { type: "string" },
          action: { type: "string" },
          impact: { type: "string", enum: ["élevé", "moyen", "faible"] },
          complexity: { type: "string", enum: ["élevé", "moyen", "faible"] },
          delay: { type: "string", enum: ["court terme", "moyen terme", "long terme"] },
          dependencies: { type: "array", items: { type: "string" } },
        },
        required: ["when", "action", "impact", "complexity", "delay", "dependencies"],
        additionalProperties: false,
      },
    },
    recommendedFormats: { type: "array", items: { type: "string" } },
    relays: {
      type: "array",
      items: {
        type: "object",
        properties: { role: { type: "string" }, mission: { type: "string" } },
        required: ["role", "mission"],
        additionalProperties: false,
      },
    },
    kpis: {
      type: "array",
      items: {
        type: "object",
        properties: { indicator: { type: "string" }, target: { type: "string" }, timing: { type: "string" } },
        required: ["indicator", "target", "timing"],
        additionalProperties: false,
      },
    },
    risks: {
      type: "array",
      items: {
        type: "object",
        properties: { risk: { type: "string" }, level: { type: "string", enum: ["élevé", "moyen", "faible"] }, mitigation: { type: "string" } },
        required: ["risk", "level", "mitigation"],
        additionalProperties: false,
      },
    },
    quickWins: { type: "array", items: { type: "string" } },
    governance: { type: "string" },
    generatedContent: {
      type: "object",
      properties: {
        executiveEmail: { type: "string" },
        intranetPost: { type: "string" },
        managerKit: { type: "string" },
        faq: { type: "string" },
      },
      required: ["executiveEmail", "intranetPost", "managerKit", "faq"],
      additionalProperties: false,
    },
    scenarios: {
      type: "array",
      items: {
        type: "object",
        properties: {
          name: { type: "string", enum: ["Essentiel", "Renforcé", "Signature"] },
          description: { type: "string" },
          actions: { type: "array", items: { type: "string" } },
        },
        required: ["name", "description", "actions"],
        additionalProperties: false,
      },
    },
    maturityScores: {
      type: "object",
      properties: {
        communication: { type: "number" },
        engagement: { type: "number" },
        changeReadiness: { type: "number" },
        label: { type: "string" },
      },
      required: ["communication", "engagement", "changeReadiness", "label"],
      additionalProperties: false,
    },
    reactionSimulation: {
      type: "object",
      properties: {
        managers: { type: "string" },
        collaborators: { type: "string" },
        terrain: { type: "string" },
        mainRisk: { type: "string" },
      },
      required: ["managers", "collaborators", "terrain", "mainRisk"],
      additionalProperties: false,
    },
    challengeMode: {
      type: "object",
      properties: {
        critique: { type: "string" },
        blindSpots: { type: "array", items: { type: "string" } },
        alternatives: { type: "array", items: { type: "string" } },
      },
      required: ["critique", "blindSpots", "alternatives"],
      additionalProperties: false,
    },
    dircomView: {
      type: "object",
      properties: {
        summary: { type: "string" },
        keyRisks: { type: "array", items: { type: "string" } },
        keyArbitrations: { type: "array", items: { type: "string" } },
        decisionsToMake: { type: "array", items: { type: "string" } },
      },
      required: ["summary", "keyRisks", "keyArbitrations", "decisionsToMake"],
      additionalProperties: false,
    },
    eventCopilot: {
      type: "object",
      properties: {
        strategicIntent: { type: "string" },
        primaryEventFormats: {
          type: "array",
          items: {
            type: "object",
            properties: {
              category: { type: "string", enum: ["sensibilisation-changement", "mise-en-oeuvre", "nouvelle-organisation", "onboarding", "communication-crise", "engagement-commercial", "celebration-reconnaissance", "dispositifs-permanents"] },
              format: { type: "string" },
              relevanceScore: { type: "number" },
              whyRecommended: { type: "string" },
              expectedImpact: { type: "string" },
              usageContext: { type: "string" },
              implementationLevel: { type: "string", enum: ["léger", "intermédiaire", "structurant"] },
            },
            required: ["category", "format", "relevanceScore", "whyRecommended", "expectedImpact", "usageContext", "implementationLevel"],
            additionalProperties: false,
          },
        },
        secondaryEventFormats: {
          type: "array",
          items: {
            type: "object",
            properties: {
              category: { type: "string", enum: ["sensibilisation-changement", "mise-en-oeuvre", "nouvelle-organisation", "onboarding", "communication-crise", "engagement-commercial", "celebration-reconnaissance", "dispositifs-permanents"] },
              format: { type: "string" },
              relevanceScore: { type: "number" },
              whyRecommended: { type: "string" },
              expectedImpact: { type: "string" },
              usageContext: { type: "string" },
              implementationLevel: { type: "string", enum: ["léger", "intermédiaire", "structurant"] },
            },
            required: ["category", "format", "relevanceScore", "whyRecommended", "expectedImpact", "usageContext", "implementationLevel"],
            additionalProperties: false,
          },
        },
        permanentCommunicationDevices: {
          type: "array",
          items: {
            type: "object",
            properties: {
              category: { type: "string", enum: ["sensibilisation-changement", "mise-en-oeuvre", "nouvelle-organisation", "onboarding", "communication-crise", "engagement-commercial", "celebration-reconnaissance", "dispositifs-permanents"] },
              format: { type: "string" },
              relevanceScore: { type: "number" },
              whyRecommended: { type: "string" },
              expectedImpact: { type: "string" },
              usageContext: { type: "string" },
              implementationLevel: { type: "string", enum: ["léger", "intermédiaire", "structurant"] },
            },
            required: ["category", "format", "relevanceScore", "whyRecommended", "expectedImpact", "usageContext", "implementationLevel"],
            additionalProperties: false,
          },
        },
        recommendedMix: { type: "string" },
        whyTheseFormats: { type: "string" },
        eventRoleInStrategy: { type: "string" },
        beforePhase: { type: "string" },
        duringPhase: { type: "string" },
        afterPhase: { type: "string" },
        managerActivation: { type: "string" },
        participantExperience: { type: "string" },
        eventStorytelling: { type: "string" },
        watchouts: { type: "array", items: { type: "string" } },
        formatsToAvoid: { type: "array", items: { type: "string" } },
      },
      required: [
        "strategicIntent", "primaryEventFormats", "secondaryEventFormats",
        "permanentCommunicationDevices", "recommendedMix", "whyTheseFormats",
        "eventRoleInStrategy", "beforePhase", "duringPhase", "afterPhase",
        "managerActivation", "participantExperience", "eventStorytelling",
        "watchouts", "formatsToAvoid",
      ],
      additionalProperties: false,
    },
    briefSpecificity: {
      type: "object",
      properties: {
        whatMakesThisCaseUnique: { type: "array", items: { type: "string" } },
        whyThisRecommendationFits: { type: "string" },
        whatWasDeliberatelyExcluded: { type: "array", items: { type: "string" } },
      },
      required: ["whatMakesThisCaseUnique", "whyThisRecommendationFits", "whatWasDeliberatelyExcluded"],
      additionalProperties: false,
    },
  },
  required: [
    "projectType", "executiveSummary", "communicationDiagnostic", "centralProblem",
    "strategicAngle", "deviceArchitecture", "audienceMessages", "channelMix",
    "keyMessages", "timeline", "recommendedFormats", "relays", "kpis", "risks",
    "quickWins", "governance", "generatedContent", "scenarios",
    "maturityScores", "reactionSimulation", "challengeMode", "dircomView", "eventCopilot",
    "briefSpecificity",
  ],
  additionalProperties: false,
};

